//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Gerenciamento_Cafeteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faturas
    {
        public int id { get; set; }
        public string uuid { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string numeroContato { get; set; }
        public string metodoPagamento { get; set; }
        public Nullable<int> valorTotal { get; set; }
        public string detalhesProduto { get; set; }
        public string criadoPor { get; set; }
    }
}
