//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Gerenciamento_Cafeteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<int> categoriaId { get; set; }
        public string descricao { get; set; }
        public Nullable<int> preco { get; set; }
        public string status { get; set; }
    }
}
